export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const LOAD_RECORDS = "LOAD_MESSAGES";
export const REMOVE_RECORDS = "REMOVE_RECORDS";